services:

  #Node 1
  re1:
    image: redislabs/redis:latest
    container_name: re1
    restart: unless-stopped
    tty: true
    cap_add: 
      - sys_resource
    ports:
      - "8443:8443"
      - "12000:12000"
      - "9443:9443"
    networks:
      app_net:
        ipv4_address: 192.168.20.2

  #Node 2
  re2:
    image: redislabs/redis:latest
    container_name: re2
    restart: unless-stopped
    tty: true
    cap_add: 
      - sys_resource
    networks:
      app_net:
        ipv4_address: 192.168.20.3

  #Node 3
  re3:
    image: redislabs/redis:latest
    container_name: re3
    restart: unless-stopped
    tty: true
    cap_add: 
      - sys_resource
    networks:
      app_net:
        ipv4_address: 192.168.20.4
  
#Docker Networks
networks:
  app_net:
    name: re_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24